# Generated by Django 6.0.4 on 2026-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('men', 'Men'), ('boys', 'Boys')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='category_type',
            field=models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms')], default='Top', max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
