# Generated by Django 6.0.4 on 2026-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_remove_product_category_product_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(choices=[('Jeans', 'Jeans'), ('Tees', 'Tees'), ('Polos', 'Polos'), ('shirts', 'shirts'), ('shorts', 'shorts')], default='Jeans', max_length=10),
        ),
    ]
